# Generated by Django 4.2.7 on 2024-04-30 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usersapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
