# Generated by Django 4.2.7 on 2024-02-14 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workdetail",
            name="work_id",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
        migrations.DeleteModel(
            name="WorkDetail",
        ),
    ]
