# Generated by Django 4.2.7 on 2024-02-14 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker_app", "0003_work_workdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "รอรับอะไหล่"),
                            ("2", "กำลังซ่อม"),
                            ("3", "ซ่อมเสร็จสิ้น"),
                        ],
                        default=1,
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=255)),
                ("lastname", models.CharField(blank=True, max_length=255)),
                ("car_part", models.CharField(blank=True, max_length=255)),
                ("car_brand", models.CharField(blank=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="workdetail",
            name="work",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
        migrations.DeleteModel(
            name="WorkDetail",
        ),
        migrations.AddField(
            model_name="assignwork",
            name="work_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="worker_app.workrequest"
            ),
        ),
        migrations.AddField(
            model_name="assignwork",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="worker_app.worker"
            ),
        ),
    ]
