# Generated by Django 4.2.7 on 2024-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0004_assignwork_workrequest_remove_workdetail_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="image",
            field=models.ImageField(blank=True, upload_to="worker"),
        ),
    ]
