# Generated by Django 4.2.7 on 2024-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0005_worker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrequest",
            name="status",
            field=models.CharField(
                choices=[("1", "รอยืนยัน"), ("2", "ยืนยันแล้ว")],
                default=1,
                max_length=20,
            ),
        ),
    ]
