# Generated by Django 4.2.7 on 2024-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0006_workrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "รอรับอะไหล่"),
                    ("2", "เช็คสภาพอะไหล่"),
                    ("3", "กำลังซ่อม"),
                    ("4", "ซ่อมเสร็จสิ้น"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
