# Generated by Django 4.2.7 on 2024-03-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0008_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="worker_app.workrequest"
            ),
        ),
    ]
