# Generated by Django 4.2.7 on 2024-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0009_alter_bill_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignwork",
            name="end_date",
            field=models.DateTimeField(),
        ),
    ]
