# Generated by Django 4.2.7 on 2024-04-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0010_alter_assignwork_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignwork",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
