# Generated by Django 4.2.7 on 2024-05-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0011_alter_assignwork_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
