# Generated by Django 4.2.7 on 2024-05-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0012_workrequest_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignwork",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="update",
        ),
        migrations.AddField(
            model_name="assignwork",
            name="update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
