# Generated by Django 4.2.7 on 2024-05-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "worker_app",
            "0013_remove_assignwork_end_date_remove_workrequest_update_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workrequest",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
