# Generated by Django 4.2.7 on 2024-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0015_alter_assignwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignwork",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "กำลังดำเนินการ"),
                    ("2", "เสร็จสิ้น"),
                    ("3", "ถูกยกเลิก"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
