# Generated by Django 4.2.7 on 2024-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0016_assignwork_end_date_alter_assignwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignwork",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
