# Generated by Django 4.2.7 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0017_assignwork_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "กำลังดำเนินการ"),
                    ("2", "กำลังดำเนินการ"),
                    ("3", "เสร็จสิ้น"),
                    ("4", "ถูกยกเลิก"),
                ],
                default=1,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "รอยืนยัน"),
                    ("2", "กำลังดำเนินการ"),
                    ("3", "เสร็จสิ้น"),
                    ("4", "ถูกยกเลิก"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
