# Generated by Django 4.2.7 on 2024-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker_app", "0019_alter_assignwork_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "กำลังดำเนินการ"),
                    ("2", "กำลังดำเนินการ"),
                    ("3", "เสร็จสิ้น"),
                    ("4", "ถูกยกเลิก"),
                    ("5", "เลยกำหนด"),
                ],
                default=2,
                max_length=20,
            ),
        ),
    ]
