# Generated by Django 4.2.7 on 2023-12-20 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="order_id",
            new_name="cart_id",
        ),
        migrations.RenameField(
            model_name="cartdetail",
            old_name="order",
            new_name="cart",
        ),
    ]
