# Generated by Django 4.2.7 on 2023-12-20 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "userinterface",
            "0002_alter_product_picture_alter_product_price_orders_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdetail",
            old_name="cart",
            new_name="order",
        ),
    ]
