# Generated by Django 4.2.7 on 2024-06-04 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userinterface", "0006_addstock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addstock",
            name="updated",
        ),
    ]
