# Generated by Django 4.2.7 on 2024-06-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userinterface", "0007_remove_addstock_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="addstock",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addstock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="userinterface.product",
            ),
        ),
    ]
