# Generated by Django 4.2.7 on 2024-02-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    (1, "รอผู้ดูแลยืนยันคำสั่งซื้อ"),
                    (2, "กำลังส่ง"),
                    (3, "ทำการส่งเรียบร้อย"),
                    (4, "ผู้ใช้รับสินค้าแล้ว"),
                    (5, "คำสั่งซื้อถูกยกเลิก"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
