# Generated by Django 4.2.7 on 2024-02-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "ยังไม่ได้ชำระ"),
                    ("2", "กำลังตรวจสอบสลิป"),
                    ("3", "กำลังเตรียมสินค้า"),
                    ("4", "กำลังนำสินค้าไปส่ง"),
                    ("5", "ทำการส่งเรียบร้อย"),
                    ("6", "ผู้ใช้รับสินค้าแล้ว"),
                    ("7", "คำสั่งซื้อถูกยกเลิก"),
                    ("8", "ยังไม่ได้ส่งสลิป"),
                ],
                default=1,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="slip")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_order.order",
                    ),
                ),
            ],
        ),
    ]
