# Generated by Django 4.2.7 on 2024-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0007_alter_order_status_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="image",
            field=models.ImageField(blank=True, upload_to="payment"),
        ),
    ]
