# Generated by Django 4.2.7 on 2024-02-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userinterface", "0004_remove_orders_customer_delete_orderdetail_and_more"),
        ("user_order", "0008_alter_payment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="product_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="userinterface.product",
            ),
            preserve_default=False,
        ),
    ]
