# Generated by Django 4.2.7 on 2024-02-14 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0009_orderdetail_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="product_id",
        ),
    ]
