# Generated by Django 4.2.7 on 2024-02-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userinterface", "0004_remove_orders_customer_delete_orderdetail_and_more"),
        ("user_order", "0010_remove_orderdetail_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userinterface.product"
            ),
        ),
    ]
