# Generated by Django 4.2.7 on 2024-02-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0011_orderdetail_updated_alter_orderdetail_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "ยังไม่ได้ชำระ"),
                    ("2", "กำลังตรวจสอบสลิป"),
                    ("3", "กำลังเตรียมสินค้า"),
                    ("4", "กำลังนำสินค้าไปส่ง"),
                    ("5", "ทำการส่งเรียบร้อย"),
                    ("6", "ผู้ใช้รับสินค้าแล้ว"),
                    ("7", "คำสั่งซื้อถูกยกเลิก"),
                    ("8", "สลิปไม่ถูกต้อง"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
