# Generated by Django 4.2.7 on 2024-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_order", "0013_order_complete_order_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
